[module]
  noProxy = "none"
  private = "*.*"
  proxy = "direct"

  [module.hugoVersion]
    extended = true
    max = "0.66.0"
    min = ""

  #[[module.imports]]
  #  disable = false
  #  ignoreConfig = false
  #  path = "gitlab.com/neotericdesign-tools/cosette"

  #[[module.imports]]
  #  path = "my-shortcodes"

[[module.mounts]]
    source = "layouts"
    target = "layouts"
